### ISSUE TITLE
BUG: Special Character inserted into ^First ^letter @ ^console if a bound key is used :)

### ISSUE THREAD

**Issue by onethree7** [ezQuake/ezquake-source#101]
Hi Team EzQuake <3
sorry, another little Bug i found.

- First Letter in Console gets promoted to "special Character", resulting in weird typos :)
- If none of you swedish people experience this bug, it could be related to keyboard mappings? (win7, german keyboard, bug is present since early ezq3 alphas.)

Reproduce by:
-----------------
open ezquake3
map dm4
now press exaclty once "W" or a movementkey of your choice
press tilde (to open console)
try to type the word "ok"

this results in my "ok" ending up as a "tk" with a colored "t" 

I´ve attached a screen, to demonstrate how it looks.
![ezquake002](https://cloud.githubusercontent.com/assets/17409572/16281596/628f218e-38c5-11e6-8e62-e2853ad8c2be.png)

**Comment by meag** [comment]
Thanks for report - can confirm that this affects systems where the console toggle key is also a dead key.  Windows is doing the translation, not Quake - we see the o key pressed, and then get sent ô, which replaces it.  SDL2 doesn't currently detect deadkeys correctly, so we actually have two bugs - if you set con_tilde_mode 1, you can replicate this on any keyboard by pressing the ^ key and then o, you'll see the deadkey produce a letter and then the ô (which in Quake is the brown t character).  The reason "now press exactly once "W" or a movementkey of your choice" is required is because otherwise you've double-tapped ^, windows produces ^^ which is ignored as you're still in the game, and then Windows is out of its deadkey-mode and the next letter appears correctly.

Working around this is going to be a headache, we get one event for the key pressed (which is always in American layout) and another with the translation to the locale.  So I can't just ignore the second event, because then when you press z on a german layout you'll get the letter y appearing on your screen.  I'll need to think about it some more.

Workarounds at the moment would be:

- Creating a layout in windows where ^ is not a dead key (Keyboard Layout Creator for Windows)
- Binding a different key to toggleconsole

My preferred solution at the moment is to ignore the translation on first keypress after toggling console, if it produces a character code >= 128.  And that's using 'preferred' loosely - everything else I have thought of is even worse.

All other suggestions welome...

**Comment by onethree7** [comment]
meag, Thank you for the answer and very good explanation of what´s happening!!
maybe i have a super lame mega cheap way of getting rid of this :dancer: 

What if you auto-send an "backspace" the moment a player requests console? That would clear the special character that would be coming up on next keypress i believe, wouldn´t it? :)

I couldn´t think of any negative sideaffects at the moment, f.e. if a player would use backspace as a "say hi" or even "+attack", that wouldn´t be triggered when console is down.

**Comment by meag** [comment]
Thanks @onethree7, I had considered faking input from the operating system level but then ezquake would have received another copy, so I'd have to ignore it - didn't know backspace cancels the deadkey state, so that might work well.  I'll give it a test this weekend.
