### ISSUE TITLE
BUG: gl_multisample

### ISSUE THREAD

**Issue by Jissse** [ezQuake/ezquake-source#155]
When changing gl_mutlisample in_game, it crashes ezquake with no more infos. If I change it in the menu and then load a map, no problem. Happening on a GTX 970, all drivers up to date.

**Comment by mmavova** [comment]
I cannot reproduce this. Changing gl_mutlisamples to a non-zero value makes qw super slow though. No crash here, Linux GTX 760.

**Comment by jite** [comment]
I can reproduce it, it's due to not finding support for it basically and thus fails to create a SDL Window (+ a string compare on a non-initialized string due to the above failure). I've pushed a fix for this, it will exit with a message if it happens now. However I'm think of implementing a check for multisample setting and reset it to 0 and then try again if it failed to avoid crashes.

**Comment by jite** [comment]
Should be properly fixed with e787a3b588d3b2250957ca95a26b4e752603fb5d hopefully
