### ISSUE TITLE
REQ: Make game brighter without hw gamma

### ISSUE THREAD

**Issue by Calinou** [ezQuake/ezquake-source#178]
I use Linux (with the NVIDIA driver), and I would like to make the game brighter without using gamma (which changes the gamma of all displays, which is not suited to multi-monitor setups as well as playing in a window).

Are there plans to implement a setting to make the map brighter, or GLSL color correction (which does not suffer from the issues of setting hardware gamma)? I don't want to use fullbright, but I do want a brighter map and HUD elements.

**Comment by mmavova** [comment]
I think everybody wants this.

**Comment by jite** [comment]
Thanks for the request. For future reference, please read the wiki on how to prefix issues.

**Comment by Matrix-QW** [comment]
gl_modulate does what you want., changes map brigthness.
Don't know if that variable exists in linux.

**Comment by jite** [comment]
Yes I have been experimenting with GLSL gamma shaders instead of resorting to hardware gamma. Though it was like a 50% performance hit doing it as a post process gamma shader, so I didn't feel it was worth it. It hasn't been forgotten though as I totally agree that hwgamma is sub-optimal.

We really need a good OpenGL engineer on the team as none of us has the proper knowledge to bring the renderer into the new millennium...

**Comment by meag** [comment]
Closing - fixed in 3.6 (`/vid_software_palette`, available without framebuffers now)
https://github.com/ezQuake/ezquake-source/commit/9de03c48ebcacf721c864384a1f61c41839ecac9
