### ISSUE TITLE
BUG: alt-tab doesn't work (Ubuntu 16.10)

### ISSUE THREAD

**Issue by drzel** [ezQuake/ezquake-source#181]
Tested on 16.10, alt-tab doesn't work in either full screen or window.

**Comment by jite** [comment]
Thanks for reporting, will get back to you shortly. In the mean time please report what window manager you are running. (Also take a look at the wiki on how to prefix issues for future reference, thanks)

**Comment by mmavova** [comment]
Isn't this the locking of the keyboard bug? I recall there was a switch.
Try
vid_grab_keyboard                    "0"

**Comment by drzel** [comment]
@jite Thanks! I'll check the wiki.

Running unity, seems to be a regression as 3.0 seems to alt-tab fine. I am able to alt-tab, only in windowed mode, and only while the console is displayed.

@mmavova  `vid_grab_keyboard` isn't recognised at all.

**Comment by jite** [comment]
Make sure you're running the latest version, not having `vid_grab_keyboard` strongly suggests you're running an older version.

**Comment by drzel** [comment]
I'm using the latest 3.0.1 release, if you mean the nightly build, then no I'm not using that.

Here is a screenshot showing the version and a print of all the available `vid_` commands: http://i.imgur.com/MeLKh7u.jpg

**Comment by jite** [comment]
Yeah the change is made after the 3.0.1 release. Please try the latest nightly build (or in your case even better if you could compile it yourself). There was a change made to grab the keyboard input, cause in some VM's otherwise special key bindings would trigger things in the VM. However a side effect of that is that alt-tab stopped working.

So IIRC I changed so that on Linux keyboard grab is disabled by default.

**Comment by drzel** [comment]
Cool, looks like nightly builds are only Windows and OS X, had some trouble compiling, I'll ping you on IRC and post results here.

**Comment by jite** [comment]
`vid_grab_keyboard 0` solved the issue, closing this.
