### ISSUE TITLE
ISSUE: Review use of _DEBUG, 'debug build' reported in nightlies, etc

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#305]

**Comment by eb** [comment]
How about we create a true debug and a true release build? Leave .config_windows as is (but without the _DEBUG define) and create a .config_windows_debug that does an unoptimized build with symbols and build both in the nightlies?

**Comment by ciscon** [comment]
fyi, i created the .config_windows-clang config as there were performance problems with the gcc mingw build when compared with the vs builds (whether debug was on or not) so that's what my builds are using now.  the combined build was particularly bad, the current "official" windows build is like this, you can compare it to the clang mingw build against the gcc build and see the performance difference, and combined versus separate renderer builds as well.  i'm not sure if switching the mingw stuff to 64 bit would address either issue, gcc or combined, i was unable to find all the static libraries required to test that.
