### ISSUE TITLE
Build instructions for OS X

### ISSUE THREAD

**Issue by marcstreeter** [ezQuake/ezquake-source#31]
I'd love to try this out on OS X -- but there aren't any build instructions. I can paste my build errors if that'd help.

**Comment by jite** [comment]
Added initial OSX compilation instructions. However the exporting of PKG_CONFIG_PATH etc wasn't necessary for me on 10.10, since curl is already installed on the system by default. When installing some extra sdl2 packages like sdl2_net etc you will get pkg-config as a dependency to that already. Thanks @marcstreeter

**Comment by sadfuzzy** [comment]
how did you fixed  "Error: Couldn't load gfx/palette.lmp"?
