### ISSUE TITLE
join and observe ignore password

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#364]
when a server has password to join as a player and/or spectating, there's some problems:
* /join or /observe doesn't work as intended
* spectator 1 and /reconnect doesn't work. 

the only thing that works to spectate a game in a server that has a password, is ofc setting the password (/spectator_password doesn't seem to work), /spectator **0** and connect. then, if the game is running, the server will automatically allow you to connect as a spectator. but it doesn't allow you to connect directly to spectate.

**Comment by meag** [comment]
I think these are mvdsv bugs/issues you're reporting

- `/spectator_password` is server variable only, to specify a spectator password you should enter `/spectator password` instead of `/spectator 1`
- `/join` & `/observe` are blocked server-side (I don't immediately know why, but that's where the error is)

**Comment by mushis** [comment]
Sorry for the late reply.
i was in doubt. i ended up creating them in ezQ, wrongly ;) 
thanks *
