### ISSUE TITLE
BUG: /fontload says "Cannot change font during match" while disconnected

### ISSUE THREAD

**Issue by paddern** [ezQuake/ezquake-source#414]
**ezQuake version:**
3.6-dev-alpha3 6822~18553fee (32 bit VS build)

**OS/device including version:**
Win 10.0.19042.572; FreeType 2.10.4

**Describe the bug**
Fonts cannot be loaded, even when not in a match.

**To Reproduce**
1. Start ezQuake
2. Try /fontload times.ttf
3. "Cannot change font during match"

**Expected behavior**
Font of choice being loaded.

**Comment by hemostx** [comment]
```
if (Rulesets_RestrictPacket()) {
		Con_Printf("Cannot change font during match\n");
		return false;
	}
```
I'm wondering why this is controlled by restrictpacket and not say, blockhudimages (or controlled at all, in fact).
Workaround is to use the default ruleset, where restrictPacket isn't limited.

**Comment by meag** [comment]
Hi

Thanks to both of you.  Two bugs here - I'll get them fixed tonight.

1) Win32 VS build isn't defining EZ_FREETYPE_SUPPORT_STATIC, so it's looking to link to a .dll
2) Rulesets_RestrictPacket() isn't checking if you're live on a server, so on initial startup it's blocked

It's controlled by RestrictPacket() because someone could replace freetype.dll with myitemtimer.dll and you're letting someone bind a key to run their own C code.

Thanks,
meag
