### ISSUE TITLE
BUG: rendering of sky (& turb?) surfaces on instanced models is broken (classic)

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#426]
**ezQuake version:**
3.5, 3.6 etc

**OS/device including version:**
Classic renderer only, it seems

**Describe the bug**
Submodels of the map with sky surfaces are drawn incorrectly

**To Reproduce**
1. `gamedir fortress`
2. `map z7`
3. join a team & class
4. go in and out of the ammo room

**Expected behavior**
Sky surfaces shouldn't show through the walls, for a start.

**Screenshots**
![image](https://user-images.githubusercontent.com/10936291/98869361-9252d480-2469-11eb-80e1-d5cc5d573357.png)

**Additional context**
Reported in #416

**Comment by Pulseczar1** [comment]
I just tested the latest ``master`` branch, and could not get this problem to happen on the machine it happened on before. I then tested the binary where the problem was seen before, and I saw the problem again. I then went back to the latest version, and couldn't get the problem to happen again. Tested for 5 or 10 minutes. I didn't see the problem at all in the current version of ``master``.
