### ISSUE TITLE
BUG: e2m1 lighting wrong 

### ISSUE THREAD

**Issue by uthiel** [ezQuake/ezquake-source#540]
Note : Potential duplicate of #439 

**ezQuake version:**
Problem was introduced in commit 
6648eb64083355e65834bbf8f20bf98007eb4198 

**OS/device including version:**
macOS 11.2.1 iMac18,3 Radeon Pro 575 OpenGL 4.2.5 
macOS 10.14.6 MacBookPro11,3  GT750M OpenGL 2.1 

vid_renderer 0 (1 is not available on both machines)

**Describe the bug**
on first map load e2m1 is wrongly lit. 
vid_restart fixes the problem. 

<img width="2560" alt="e2m1-bad" src="https://user-images.githubusercontent.com/1815599/113427612-a45ff000-93d5-11eb-8934-c4e157b03767.PNG">

**To Reproduce**
1. download current master
2. make
3. add pak1.pak
4. ./ezquake-darwin-x86_64 
5. Start Single Player
6. Enter e2m1

**Expected behavior**
lighting should look like this:
<img width="2560" alt="e2m1-ok" src="https://user-images.githubusercontent.com/1815599/113427666-c22d5500-93d5-11eb-9b6a-03920f566214.PNG">

**Comment by meag** [comment]
Can confirm on default quake install ... on my saved config, this was not happening, will need to investigate further

Debugging message from drivers:
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 2 GLD_TEXTURE_INDEX_2D_ARRAY is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable

**Comment by meag** [comment]
Hi - hopefully fixed now but re-open if not

**Comment by uthiel** [comment]
Crashes with

`Error: Unable to create lightmap texture array: error 1282`

**Comment by meag** [comment]
Hi @uthiel

Okay, the lightmap array code is causing a system error at that point even if something prior actually caused the error (rather than just loading and using an incomplete texture, as before).  I was getting 1280 (GL_INVALID_ENUM) but 1282 is GL_INVALID_OPERATION, so something else is failing on your machine/config.

Can you try compiling with WITH_RENDERING_TRACE defined (I added to makefile but depends how you're configured), and then run again with `-dev -r-trace` in the command line?  It will really hurt your fps but afterwards there should be a folder in your qw directory called `trace`, containing all the OpenGL rendering calls for each frame - please zip this up and upload.  Hopefully one will say ERROR and we can trace it back from there.

You might find that when running with `-r-trace` it doesn't crash on loading e2m1, as the error is being consumed earlier - just terminate at that point anyway, we don't need it to crash, just to get the error in the log.

Thanks,
meag

**Comment by uthiel** [comment]
Couldn't find `WITH_RENDERING_TRACE` anywhere in `Makefile` so I just appended it to `CFLAGS`.

There was indeed no crash now, and we got a `ERROR: glTexSubImage3D (UNKNOWN_ERROR 0x502)` hope that helps.

[trace.zip](https://github.com/ezQuake/ezquake-source/files/6758558/trace.zip)

**Comment by meag** [comment]
Hi @uthiel 

Not sure if you get pinged when a commit is added but just incase not, if you could try again please.

Still an issue with `/r_drawflat 1` and the first load of e2m1 (the area under the first grunt had all-black surfaces) which I'll look into.

**Comment by uthiel** [comment]
You fixed it, great work!

PS: No I didn't get pinged.
