### ISSUE TITLE
REQ: Add turn left/right to menu (also buggy and inconsistent turning)

### ISSUE THREAD

**Issue by veganaize** [ezQuake/ezquake-source#550]
There doesn't seem to be an option to set the controls for **turning** left and right.

It sure would be nice if **Options -> Controls -> Movement** offered a setting for "_Turn Left_" and "_Turn Right_".

Currently it requires manual binding at the console or in a config file:
```
bind leftarrow +left
bind rightarrow +right
```

![no_turning](https://user-images.githubusercontent.com/7102064/116652892-f6475780-a93a-11eb-8c0c-bca9fe94d0ff.png)

**Comment by Calinou** [comment]
These settings are rarely used and may be confused with "Strafe Left" and "Strafe Right", so I'm not sure if these should be exposed in the menu.

**Comment by veganaize** [comment]
Sometimes I use the arrow keys when I need to do a precise movement -- like walking on a ledge.  But it's okay...  I realize my frustration doesn't matter.  After manually setting the keys, myself, I also realized how buggy and inconsistent ezQuake's turning actually is.  So I just deleted the whole thing and installed a real client.

**Comment by meag** [comment]
Hi @veganaize can you give more detail on "buggy and inconsistent"?  If it's mostly single player you're after though then other clients are probably a better choice.

**Comment by veganaize** [comment]
1. Enable keyboard turning with the commands above.
2. Start a single player game.
3. Walk straight down the hall and enter the episode selection room.
4. Stand in the center of that room and spin in circles by holding the key bound to turn left or right.

The first issue is that turning is way, way too slow (even at the "default").  This can be remedied by adjusting the yaw speed (`cl_yawspeed`, if I remember correctly).

The other issue is that, on my display (1280x720px), put simply, episode 4's entrance spins by at a different rate than the rest of the room.

**Comment by veganaize** [comment]
I'm NOT after mostly single-player.  It's 50/50 single and multiplayer -- but that's irrelevant, as I traverse ledges in both.  I don't see how such an essential setting could confuse the already horrendously dense options menu.  It could be argued that "swim up" and "swim down" are even more redundant as I imagine that most players have mouselook always enabled; they can also use the jump key to effective swim up.

It's also frustrating how easy it is to accidently reset the settings when trying to save them...  A confirmation prompt could serve well there.

Thanks.

**Comment by HangTimeQW** [comment]
Swimdown isn't redundant as you need it to move down whilst not looking down (e.g. during combat).  This is used in the majority of dm3 rounds I play.
Swimup is 'more redundant' but not completely until such time as smartjump quirks are fixed (jumping into water and holding jump doesn't swimup)- good example is when leaving RL room on obsidian via water, if you jump in then you have to release and repress jump in order to swim up.

FWIW I think there is a case for having turn left/right/up/down in the menu, but it's an extremely niche case and these commands are banned under competitive rulesets anyway due to the potential for movement scripts.  So it could be a bit confusing for people to have commands in the menu that are banned.

**Comment by veganaize** [comment]
You rock @meag !
