### ISSUE TITLE
REQ: Validate config against documentation (was: hud_teamholdinfo_style > 2 does not draw anything)

### ISSUE THREAD

**Issue by Ch0wW** [ezQuake/ezquake-source#82]
When values superior to 2 is set, it doesn't draw anything (since it only checks "==" conditions in SCR_HUD_DrawTeamHoldInfo )

This fix should be trivial to implant:

In hud_common.c, line 4858:
`else if(hud_teamholdinfo_style->value == HUD_TEAMHOLDINFO_STYLE_PERCENT_BARS2)`
should be fixed by using:
`else if(hud_teamholdinfo_style->value >= HUD_TEAMHOLDINFO_STYLE_PERCENT_BARS2)`

Screenshots below.
![glqwcl 2016-04-12 02-14-23-70](https://cloud.githubusercontent.com/assets/2938006/14446298/4664a832-004c-11e6-9ac4-a5d66d020098.png)

![glqwcl 2016-04-12 02-14-56-45](https://cloud.githubusercontent.com/assets/2938006/14446307/5b3185d2-004c-11e6-9cc7-13b4593be619.png)

**Comment by jite** [comment]
I'll discuss this wiht meag, it's not really a bug in my opinion because you are trying to use a style that doesn't exist. What if a user sets "style 3" which doesn't exist, and it's drawing as if "style 2". Next up we're adding a new style, which naturally will have nbr 3, then what's being drawn will change.

This way, not drawing anything if choosing a style that doesn't exist will atleast make you aware of that fact and make you set something that works (and we can safely make a style 3 without breaking things for anyone).

However the question is a bit wider here because I'm fairly sure that the behaviour differs depending on which cvar we're talking about and they should ideally behave the same all of them. We must discuss how we think it should be as a first step and then look into what we can do about unifying the behaviour.

(Sidenote: My opinion about on/off cvars is that 0 means off, any other value means on, but we might discuss this too and get back to you/others).

**Comment by meag** [comment]
Changing this to the more general point that there's no validation between your configuration and the documentation, so it's difficult to know when you've set a cvar to an invalid value.  Of course, we'll need complete documentation, otherwise that will throw up lots of erroneous warnings...
